[project]
name = "Celeste-OpenWorld-AP-Tracker-generator"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = ["pillow>=12.1.1"]

[dependency-groups]
dev = ["mypy>=1.19.1", "ruff>=0.15.1", "rumdl>=0.1.21"]

[tool.ruff]
lint.select = ["ALL"]
lint.ignore = [
    "COM", # Conflicts with formatter
    "FIX", # TODOs intentionally left in code as documentation
    "D",   # TODO(Reisz): #4 Documentation
]

[tool.mypy]
strict = true

[tool.rumdl.MD013]
line-length = 300